In [1]:
from numpy.ma.core import argmax
from numpy.testing.print_coercion_tables import print_new_cast_table
# install and version check
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)

2.4.3


In [3]:
# Converting list to array
my_list=[1,2,3,4,5]
np_array=np.array(my_list)
print(my_list)
print(np_array,"\n",type(np_array))


[1, 2, 3, 4, 5]
[1 2 3 4 5] 
 <class 'numpy.ndarray'>


In [4]:
# np array type -- Same type data in np array
print(np_array.dtype)


int64


In [5]:
# In Each dimension how many elements are there in an np array
np_array.shape


(5,)

In [6]:
# Dimension of an np array
np_array.ndim

1

In [7]:
# Creating an array with all elements zero  [ default type : float64]
np_zeros=np.zeros(
    shape=(5,4,2),
    dtype=int
)
print(np_zeros)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [8]:
# creating an array with all elements one
np_ones=np.ones(
    shape=(5,4,2),
    dtype=float
)
print(np_ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [9]:
# creating an array with a specific element
np_full=np.full(
    shape=(2,3),
    fill_value=100
)
print(np_full)

[[100 100 100]
 [100 100 100]]


In [10]:
# Identity matrix
np_identity=np.eye(5)
print(np_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# empty array - by default --
np_empty=np.empty(
    shape=(2,2)
)
print(np_empty)

[[0.00000000e+000 8.47215315e-312]
 [8.47215316e-312 8.47215316e-312]]


In [12]:
# Typecast
np_array_float=np_array.astype(float)
print(np_array_float)
print(np_array.dtype)
print(np_array_float.dtype)

[1. 2. 3. 4. 5.]
int64
float64


In [13]:
# Sequential array -- range ( stop not included )
np_range=np.arange(1,10,2)
print(np_range)

[1 3 5 7 9]


In [14]:
# Linearly spaced array ( Here stop is included) (start , stop , num)
np_linear_spaced=np.linspace(
    start=10,
    stop=20,
    num=7
)
print(np_linear_spaced)

[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333
 20.        ]


In [15]:
"""
Mathematical Objects
Scalar (OD) , Vector ( 1D) , Matrix ( 2D ) , Tensor ( xD where x >2)
Tensor : n-dimensional numpy array
"""
# Scalar
scalar=np.array(20)
print(scalar)
print(scalar.ndim)


20
0


In [16]:
# Vector
vector=np.array([1,2,3])
print(vector)
print(vector.ndim)

[1 2 3]
1


In [17]:
# Matrix
matrix=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(matrix)
print(matrix.ndim,"\n",matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2 
 (3, 3)


In [18]:
# Tensor
tensor=np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ]
    ]
)
print(tensor)
print(tensor.ndim)
print(tensor.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [19]:
# Numpy indexing  1D
my_1d_array=np.array([1,2,3,4,5])
print(my_1d_array[0])
print(my_1d_array[-5])

1
1


In [20]:
# 2D indexing
my_2d_array=np.array(
    [
        [1,2,3,13],
        [4,5,6,16],
        [7,8,9,19]
    ]
)
print(my_2d_array[2,2])
print(my_2d_array[-1,2])
print(my_2d_array.shape)

9
9
(3, 4)


In [21]:
# 3D
my_3d_array=np.array(
    [
        [
            [1,2],
            [3,4],
            [1,1]
        ],
        [   [7,8],
            [5,10],
            [1,2],

        ]
    ]
)
print(my_3d_array.shape)
print(my_3d_array[0,1,1])

(2, 3, 2)
4


In [22]:
# Slicing
print(my_1d_array)
print(my_1d_array[1:4:1])
print(my_1d_array[1::])
print(my_1d_array[::])
print(my_1d_array[::-1])


[1 2 3 4 5]
[2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[5 4 3 2 1]


In [23]:
# 2D slicing
print(my_2d_array,"\n")
print(my_2d_array[1::,1:3])


[[ 1  2  3 13]
 [ 4  5  6 16]
 [ 7  8  9 19]] 

[[5 6]
 [8 9]]


In [24]:
# 3D Slicing
print(my_3d_array,"\n")
print(my_3d_array[1::,1::,1::])

[[[ 1  2]
  [ 3  4]
  [ 1  1]]

 [[ 7  8]
  [ 5 10]
  [ 1  2]]] 

[[[10]
  [ 2]]]


In [25]:
# Reshape-- changing the shape
# Condition : number of elements must be same
# GIVEN
example=np.array(
    [
        [
           [1,2],
            [3,4]
        ],
        [
            [7,8],
            [5,10],
        ]
    ]
)
print(example.shape)
# To (4,1,2)
"""
1. Flattening the original array
flattend array=[1,2,3,5,7,8.5.10]
2. Reshaping into (4,1,2)
At dimension 0
[
  [1,2]
  [3,4]
  [7,8]
  [5,10]
]
at dimension 1
"""
example_reshaped=np.array(
[
    [
        [1,2]
    ],
    [
        [3,4]
    ],
    [
        [7,8]
    ],
    [
        [5,10]
    ]
]
)
print(example_reshaped.shape)

(2, 2, 2)
(4, 1, 2)


In [26]:
my_array=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
        [13,14,15]
    ]
)
print(my_array.shape)
# To 1,3,5
# Flatten to [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
# Dimension 0
"""
 [
  [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
 ]
# Dimension 1
"""
my_array_reshaped=np.array(
[
  [
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
  ]
 ]
)
my_array_res=my_array.reshape(1,3,5)
print(my_array_reshaped.shape)
print(my_array_res.shape)
print(my_array_res)

(5, 3)
(1, 3, 5)
(1, 3, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [27]:
# Reshape with -1
new_array=np.zeros(
    shape=(3,4,2,2),
)
# number of elements== 48
new_array_reshaped=new_array.reshape(2,2,-1)
print(new_array.shape)
print(new_array_reshaped.shape)

(3, 4, 2, 2)
(2, 2, 12)


In [32]:
# Numpy Filtering
# Boolean mask

my_1d_array=np.array([1,2,3,4,5,6])
filter_mask=[True,False,False,True,False,True]

filtered_array=my_1d_array[filter_mask]
print(filtered_array)


[1 4 6]


In [34]:
# Indexing- List Filtering
print(my_1d_array[[5,2,1]])

[6 3 2]


In [35]:
indices=[0,2,5]
filtered_array=my_1d_array[indices]
print(filtered_array)

[1 3 6]


In [40]:
# Vectorization : process of performing operations on entire arrays or vectors without the need for explicit loops
"""
Example : my_1d_array +=5 ( only works for numpy arrays {parallely} )
"""

# Odd mask
print(my_1d_array)
odd_mask=(my_1d_array%2)
oddmask=odd_mask.astype(bool)
print(oddmask)
my_1d_array_odd=my_1d_array[oddmask]
print(my_1d_array_odd)

[1 2 3 4 5 6]
[ True False  True False  True False]
[1 3 5]


In [41]:
my_1d_array=my_1d_array+5
print(my_1d_array)

[ 6  7  8  9 10 11]


In [44]:
my_1d_array=my_1d_array*2
print(my_1d_array)

[48 56 64 72 80 88]


In [51]:
"""
ELEMENT WISE MULTIPLICATION
Broadcasting  : to convert low dimension compatible to higher dimension for doing operations
Condition: Either same size in each dimension  or one of the arrays has a size of 1 in that dimension when at most 1 mismatch position in that array
"""
w=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12]
    ]
)
x=np.array(
    [
        [ [10,20,30],
        ],
        [
            [11,12,13]
        ]
    ]
)
print(w.shape,x.shape)
x_broadcast=w*x
print(x_broadcast)
print(x_broadcast.shape)

(4, 3) (2, 1, 3)
[[[ 10  40  90]
  [ 40 100 180]
  [ 70 160 270]
  [100 220 360]]

 [[ 11  24  39]
  [ 44  60  78]
  [ 77  96 117]
  [110 132 156]]]
(2, 4, 3)


In [52]:
"""
Numpy Axis
First dim axis=0,
Second Dim axis=1
Third Dim axis=2

Nth dim axis=N-1
"""
my_np_array=np.array(
    [
        [1,5,-2],
        [0,1,9]
    ]
)
print(my_np_array.shape)


(2, 3)


In [54]:
# Sum
print(my_np_array.sum(axis=0))
print(my_np_array.sum(axis=1))

[1 6 7]
[ 4 10]


In [55]:
my_np_3d=np.array(
    [
        [
            [2,2],
            [1,1]
        ],
        [
            [3,1],
            [4,3]

        ],
        [
            [9,-2],
            [1,1]
        ]
    ]
)
print(my_np_3d.shape)

(3, 2, 2)


In [58]:
sum=np.sum(my_np_3d,axis=1)
sum.shape

(3, 2)

In [59]:
print(sum)

[[ 3  3]
 [ 7  4]
 [10 -1]]


In [60]:
sum2=np.sum(my_np_3d,axis=2)
print(sum.shape)
print(sum2)

(3, 2)
[[4 2]
 [4 7]
 [7 2]]


In [66]:
# random
# rand() : a random value between 0 and 1
# rand(2,5) : shape of 2,5 values between 0 and 1
# randint(100): single random number below 100
# randint(100,size(5,2)) : Below number 100 shape of 5,2
# shuffle : Axis 0 shuffle

print(np.random.rand())
print(np.random.rand(3,2,3))
print(np.random.rand(5))

0.7482160600601857
[[[0.00313904 0.29165882 0.44885119]
  [0.95418705 0.68106074 0.88708458]]

 [[0.22111094 0.8347224  0.98111922]
  [0.35450343 0.46476147 0.05846284]]

 [[0.72794952 0.93394608 0.59217281]
  [0.61940814 0.57363302 0.9438118 ]]]
[0.92685322 0.89438504 0.2691114  0.67441995 0.56692275]


In [70]:
print(np.random.randint(100))
print(np.random.randint(200,size=(3,2,3)))

19
[[[106  49  43]
  [132  39 117]]

 [[ 77 175  79]
  [159 172 180]]

 [[ 31 156 188]
  [ 10 120  52]]]


In [76]:
np.random.seed(42)
my_array=np.random.randint(100,size=(5,5))
print(my_array)

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]


In [80]:
np.random.shuffle(my_array)
print(my_array)

[[51 92 14 71 60]
 [87 99 23  2 21]
 [ 1 63 59 20 32]
 [20 82 86 74 74]
 [52  1 87 29 37]]


In [82]:

probabilites=np.array([0.3,0.1,0.4,0.2])
probabilites_sorted=np.sort(probabilites)
print(probabilites_sorted)
probabilites_reverse_sorted=probabilites[::-1]
print(probabilites_reverse_sorted)

[0.1 0.2 0.3 0.4]
[0.2 0.4 0.1 0.3]


In [84]:
# Argmax
# Argmin
index_max=np.argmax(probabilites)
print(index_max)
index_min=np.argmin(probabilites)
print(index_min)

2
1


In [86]:
# Split : Equal partitions
my_np_array=np.array([1,5,1,1,5,7])
splitted=np.split(
    my_np_array,
    indices_or_sections=3
)
print(splitted)
print(splitted[2])

[array([1, 5]), array([1, 1]), array([5, 7])]
[5 7]


In [89]:
# Dot product
my_np_array_1=np.array(
    [1,2,3]
)
my_np_array_2=np.array(
    [3,4,3],
)
dot_product=np.dot(my_np_array_1,my_np_array_2)
print(dot_product)

20


In [91]:
# Matrix transpose

my_2d_array=np.array(
    [
        [2,1,3],
        [7,5,6]
    ]
)
print(my_2d_array.shape)
print(my_2d_array.T.shape)
print(my_2d_array.T)

(2, 3)
(3, 2)
[[2 7]
 [1 5]
 [3 6]]


In [92]:
# mean ,median ,std

print(my_np_array_1)
print(np.mean(my_np_array_1))
print(np.median(my_np_array_1))
print(np.std(my_np_array_1))

[1 2 3]
2.0
2.0
0.816496580927726
