In [6]:
from numpy.testing.print_coercion_tables import print_new_cast_table
# install and version check
!pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.3 MB 10.2 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/12.3 MB 7.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.3 MB 6.1 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.3 MB 5.8 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 5.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.3 MB 6.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.3 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 6.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 6.0 MB/s  0:00:02



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
print(np.__version__)

2.4.3


In [11]:
# Converting list to array
my_list=[1,2,3,4,5]
np_array=np.array(my_list)
print(my_list)
print(np_array,"\n",type(np_array))


[1, 2, 3, 4, 5]
[1 2 3 4 5] 
 <class 'numpy.ndarray'>


In [13]:
# np array type -- Same type data in np array
print(np_array.dtype)


int64


In [15]:
# In Each dimension how many elements are there in an np array
np_array.shape


(5,)

In [16]:
# Dimension of an np array
np_array.ndim

1

In [21]:
# Creating an array with all elements zero  [ default type : float64]
np_zeros=np.zeros(
    shape=(5,4,2),
    dtype=int
)
print(np_zeros)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [22]:
# creating an array with all elements one
np_ones=np.ones(
    shape=(5,4,2),
    dtype=float
)
print(np_ones)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [23]:
# creating an array with a specific element
np_full=np.full(
    shape=(2,3),
    fill_value=100
)
print(np_full)

[[100 100 100]
 [100 100 100]]


In [26]:
# Identity matrix
np_identity=np.eye(5)
print(np_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
# empty array - by default --
np_empty=np.empty(
    shape=(2,2)
)
print(np_empty)

[[1. 1.]
 [1. 1.]]


In [43]:
# Typecast
np_array_float=np_array.astype(float)
print(np_array_float)
print(np_array.dtype)
print(np_array_float.dtype)

[1. 2. 3. 4. 5.]
int64
float64


In [47]:
# Sequential array -- range ( stop not included )
np_range=np.arange(1,10,2)
print(np_range)

[1 3 5 7 9]


In [51]:
# Linearly spaced array ( Here stop is included) (start , stop , num)
np_linear_spaced=np.linspace(
    start=10,
    stop=20,
    num=7
)
print(np_linear_spaced)

[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333
 20.        ]


In [54]:
"""
Mathematical Objects
Scalar (OD) , Vector ( 1D) , Matrix ( 2D ) , Tensor ( xD where x >2)
Tensor : n-dimensional numpy array
"""
# Scalar
scalar=np.array(20)
print(scalar)
print(scalar.ndim)


20
0


In [56]:
# Vector
vector=np.array([1,2,3])
print(vector)
print(vector.ndim)

[1 2 3]
1


In [60]:
# Matrix
matrix=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(matrix)
print(matrix.ndim,"\n",matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2 
 (3, 3)


In [62]:
# Tensor
tensor=np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ]
    ]
)
print(tensor)
print(tensor.ndim)
print(tensor.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)


In [63]:
# Numpy indexing  1D
my_1d_array=np.array([1,2,3,4,5])
print(my_1d_array[0])
print(my_1d_array[-5])

1
1


In [67]:
# 2D indexing
my_2d_array=np.array(
    [
        [1,2,3,13],
        [4,5,6,16],
        [7,8,9,19]
    ]
)
print(my_2d_array[2,2])
print(my_2d_array[-1,2])
print(my_2d_array.shape)

9
9
(3, 4)


In [71]:
# 3D
my_3d_array=np.array(
    [
        [
            [1,2],
            [3,4],
            [1,1]
        ],
        [   [7,8],
            [5,10],
            [1,2],

        ]
    ]
)
print(my_3d_array.shape)
print(my_3d_array[0,1,1])

(2, 3, 2)
4


In [79]:
# Slicing
print(my_1d_array)
print(my_1d_array[1:4:1])
print(my_1d_array[1::])
print(my_1d_array[::])
print(my_1d_array[::-1])


[1 2 3 4 5]
[2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[5 4 3 2 1]


In [94]:
# 2D slicing
print(my_2d_array,"\n")
print(my_2d_array[1::,1:3])


[[ 1  2  3 13]
 [ 4  5  6 16]
 [ 7  8  9 19]] 

[[5 6]
 [8 9]]


In [102]:
# 3D Slicing
print(my_3d_array,"\n")
print(my_3d_array[1::,1::,1::])

[[[ 1  2]
  [ 3  4]
  [ 1  1]]

 [[ 7  8]
  [ 5 10]
  [ 1  2]]] 

[[[10]
  [ 2]]]


In [105]:
# Reshape-- changing the shape
# Condition : number of elements must be same
# GIVEN
example=np.array(
    [
        [
           [1,2],
            [3,4]
        ],
        [
            [7,8],
            [5,10],
        ]
    ]
)
print(example.shape)
# To (4,1,2)
"""
1. Flattening the original array
flattend array=[1,2,3,5,7,8.5.10]
2. Reshaping into (4,1,2)
At dimension 0
[
  [1,2]
  [3,4]
  [7,8]
  [5,10]
]
at dimension 1
"""
example_reshaped=np.array(
[
    [
        [1,2]
    ],
    [
        [3,4]
    ],
    [
        [7,8]
    ],
    [
        [5,10]
    ]
]
)
print(example_reshaped.shape)

(2, 2, 2)
(4, 1, 2)


In [113]:
my_array=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
        [13,14,15]
    ]
)
print(my_array.shape)
# To 1,3,5
# Flatten to [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
# Dimension 0
"""
 [
  [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
 ]
# Dimension 1
"""
my_array_reshaped=np.array(
[
  [
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
  ]
 ]
)
my_array_res=my_array.reshape(1,3,5)
print(my_array_reshaped.shape)
print(my_array_res.shape)
print(my_array_res)

(5, 3)
(1, 3, 5)
(1, 3, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [117]:
# Reshape with -1
new_array=np.zeros(
    shape=(3,4,2,2),
)
# number of elements== 48
new_array_reshaped=new_array.reshape(2,2,-1)
print(new_array.shape)
print(new_array_reshaped.shape)

(3, 4, 2, 2)
(2, 2, 12)
